### ISSUE TITLE
Error fetching data: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by froxic** [yardee/ha-wattrouter#14]
Zdravim,

Po update HA core na 2023.12.4 mi to vyhazuje tuto hlasku pri startupu doplnku.

2024-01-02 23:30:59.804 ERROR (MainThread) [custom_components.wattrouter] Error fetching information from http://192.168.88.200/stat_day.xml?day=0 - [Errno 104] Connection reset by peer
2024-01-02 23:30:59.804 ERROR (MainThread) [custom_components.wattrouter] Error fetching data: a bytes-like object is required, not 'NoneType'
2024-01-02 23:30:59.806 ERROR (MainThread) [custom_components.wattrouter] Error fetching wattrouter data: 
2024-01-02 23:30:59.806 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry http://192.168.88.200/ for wattrouter
Traceback (most recent call last):
  File "/config/custom_components/wattrouter/coordinator.py", line 38, in _async_update_data
    day_stats=await self.api.get_day_stats(),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wattrouter/api.py", line 54, in get_day_stats
    return self.parser.parse_day_stats(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wattrouter/xml_parser.py", line 59, in parse_day_stats
    root = ET.fromstring(xml)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1338, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wattrouter/coordinator.py", line 43, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wattrouter/__init__.py", line 42, in async_setup_entry
    raise ConfigError("Cannot setup wattrouter") from coordinator.last_exception
homeassistant.config_entries.ConfigError: Cannot setup wattrouter

Po znovu nacteni doplnku v GUI vse najede a vypada ze funguje jak ma. Po manualnim restartu HA z UI to nekdy uz pak najede ok a nekdy ne, pak staci znovu nacist doplnek a jede to.

Pri kliknuti v hubu na nastavit to hodi chybu:
Nastavení nelze načíst: {"message":"Handler does not support user"}

Nejaky napad kde by mohl byt problem? Zase tak casto nerestartuji HA, ale rad bych chtel prijit na to, kde je zakopany pes.

Diky za super doplnek!

**Comment by yardee** [comment]
Dobrý večer,
zamergoval jsem fix, tak zkuste. Nyní to bude ignorovat chyby s připojením při nastavení integrace a bude zkoušet dále. Zároveň jsem upravil handlování chyb, aby se nevolal parser, když se nedovolá na wattrouter. Jinak si myslím, že se občas nepřipojí k wattrouteru, asi problém v síti. Můžete hledat error "Error fetching data", kde by mělo být víc detailů.

**Comment by froxic** [comment]
Dobrý večer, zkusím nahodit a dám vědět.

Kdyby byl problém na síti, tak bych předpokládal že to bude dělat spíše
náhodně a ne po startu a i opakovaně. Po kliknutí na reload i po chybě se
to vždy chytlo. WR je na stejné sítí vše na kabelu.

pá 5. 1. 2024 v 20:51 odesílatel Michal Baše ***@***.***>
napsal:

**Comment by yardee** [comment]
Ono pokud došlo k chybě při startu (tzn nastavení integrace), tak už to nikdy nezkusil znovu. Ale pokud dojde k chybě při standardním běhu, tak to zkouší stále znova. No uvidíte a dejte vědět

**Comment by froxic** [comment]
Tak vypadá to že vyřešeno. Teď to jede ihned po restartu, zkoušel jsem to
3x. Žádná chyba v logu.

pá 5. 1. 2024 v 20:58 odesílatel Michal Baše ***@***.***>
napsal:

**Comment by yardee** [comment]
Tak super
