### ISSUE TITLE
Wattrouter  nejde mi načíst integrace do home  assistenta. V čem může byt problém?

### ISSUE THREAD

**Issue by RSvorcik** [yardee/ha-wattrouter#7]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by yardee** [comment]
Potřeboval bych víc informací, jak to nastavujete a co to hlásí za chybu. Ideálně i logy.

**Comment by RSvorcik** [comment]
Dobrý den,

složku ha-wattrouter-main jen zkopíroval do složky custom_components. V 
hacs není v ,,Vlastní repozitáře,, ani nejde dohledat.




S pozdravem

Rudolf Švorčík





------ Původní zpráva ------
Od "Michal Baše" ***@***.***>
Komu "yardee/ha-wattrouter" ***@***.***>
Kopie "RSvorcik" ***@***.***>; "Author" 
***@***.***>
Datum 06.08.2023 11:36:21
Předmět Re: [yardee/ha-wattrouter] Wattrouter nejde mi načíst integrace 
do home assistenta. V čem může byt problém? (Issue #7)

**Comment by yardee** [comment]
Dobrý den,
v hacs dáte menu -> vlastní reposizáře
![image](https://github.com/yardee/ha-wattrouter/assets/10993234/02ef3583-e38d-4ab7-ae65-be7101675e4a)
Zde ho přidáte
![image](https://github.com/yardee/ha-wattrouter/assets/10993234/fc8b3c7b-10eb-45ba-b0f4-8d5bc7686d66)
(Do vstupu pro repozitář dáte url https://github.com/yardee/ha-wattrouter)
Pak by měla jít integrace nainstalovat v integracích
![image](https://github.com/yardee/ha-wattrouter/assets/10993234/1d617c36-874c-42b3-a11d-f3795b8cdf45)

**Comment by RSvorcik** [comment]
Dobrý den,

ano tak jsem to udělal,ale  tam to není. To je divné.




S pozdravem

Rudolf Švorčík





------ Původní zpráva ------
Od "Michal Baše" ***@***.***>
Komu "yardee/ha-wattrouter" ***@***.***>
Kopie "RSvorcik" ***@***.***>; "Author" 
***@***.***>
Datum 06.08.2023 11:55:03
Předmět Re: [yardee/ha-wattrouter] Wattrouter nejde mi načíst integrace 
do home assistenta. V čem může byt problém? (Issue #7)

**Comment by RSvorcik** [comment]
viz výstřižky



------ Původní zpráva ------
Od "Rudolf Švorčík" ***@***.***>
Komu "yardee/ha-wattrouter" 
***@***.***>
Datum 06.08.2023 12:08:11
Předmět Re[2]: [yardee/ha-wattrouter] Wattrouter nejde mi načíst 
integrace do home assistenta. V čem může byt problém? (Issue #7)

**Comment by yardee** [comment]
Vybral jste kategorii integrace?

**Comment by RSvorcik** [comment]
Ano je to výstřižku v předchozím emailu.


S pozdravem

Rudolf Švorčík





------ Původní zpráva ------
Od "Michal Baše" ***@***.***>
Komu "yardee/ha-wattrouter" ***@***.***>
Kopie "RSvorcik" ***@***.***>; "Author" 
***@***.***>
Datum 06.08.2023 14:53:18
Předmět Re: [yardee/ha-wattrouter] Wattrouter nejde mi načíst integrace 
do home assistenta. V čem může byt problém? (Issue #7)

**Comment by yardee** [comment]
Přílohu mailu to sem asi nepřidá, zkuste je nahrát přímo na githubu do zprávy. Zkoušel jste po přidání integrace v hacs restartovat home assistatant?

**Comment by RSvorcik** [comment]
Ano několikrát jsem to restartoval.
![Snímek obrazovky 2023-08-06 121819](https://github.com/yardee/ha-wattrouter/assets/118067350/32df2cc1-8dc9-4976-b0c9-eb63c7601323)
![Snímek obrazovky 2023-08-06 121918](https://github.com/yardee/ha-wattrouter/assets/118067350/fa70da32-a682-4489-823f-09d37e636f70)

**Comment by yardee** [comment]
Do `Repozitář`musíte dát URL repa: https://github.com/yardee/ha-wattrouter. Z něho to pak stahuje integraci

**Comment by yardee** [comment]
Z custom components bych složku ha-wattrouter-main smazal, stahuje to tam hacs

**Comment by RSvorcik** [comment]
Tak už jsem to tam dostal, ale stejně to [nejde.
![Snímek obrazovky 2023-08-07 151048](https://github.com/yardee/ha-wattrouter/assets/118067350/0a0bbbad-c20b-4334-9be8-a19dbe0c7dd5)

**Comment by yardee** [comment]
To padá v nastavení integrace? Může prosím poslat jak to konfigurejete?

**Comment by RSvorcik** [comment]
Děkuji za rady. Jsem zatím začátečník zatím to testuji  na home assistant portable 5.3 pod Win 11. Mám v plánu koupit až to rozchodím samostatný stroj asi GMK NucBox KB5 Mini-PC nebo něco podobného. Nevím jestli nemůže být chyba už v ton ,že je to verze portable.

2023-08-08 15:17:47,505.505 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform wattrouter
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 563, in _async_add_entity
    device_info = entity.device_info
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\entity.py", line 66, in device_info
    identifiers={(DOMAIN, coordinator.data.measurement.serial_number)},
AttributeError: 'NoneType' object has no attribute 'measurement'

**Comment by yardee** [comment]
Asi tam bude ještě někde jiný error. Dáváte správnou url wattrouteru do nastavení wattrouteru v integraci?

**Comment by RSvorcik** [comment]
Tak jsem zkusil zkopírovat všechny žluté a červené hlášky. Nebo mám hledat ještě jinde?
2023-08-09 08:07:43,048.048 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=65 from 2023-08-08 18:34:37.635661)
2023-08-09 08:08:23,775.775 WARNING (MainThread) [homeassistant.config_entries] Config entry 'nanogreen' for nanogreen integration not ready yet; Retrying in background
2023-08-09 08:08:23,884.884 ERROR (MainThread) [custom_components.wattrouter] Error fetching information from /meas.xml - /meas.xml
2023-08-09 08:08:23,962.962 ERROR (MainThread) [custom_components.wattrouter] Unexpected error fetching wattrouter data: can only concatenate str (not "TypeError") to str
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\coordinator.py", line 36, in _async_update_data
    measurement=await self.api.get_measurement(),
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\api.py", line 48, in get_measurement
    return self.parser.parse_measurement(response_text)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\xml_parser.py", line 23, in parse_measurement
    root = ET.fromstring(xml)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\xml\etree\ElementTree.py", line 1342, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\coordinator.py", line 42, in _async_update_data
    _LOGGER.error("Error fetching data: " + exception)
TypeError: can only concatenate str (not "TypeError") to str
2023-08-09 08:08:23,993.993 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Electricity Spot Rate in CZK/kWh' for cz_energy_spot_prices integration not ready yet; Retrying in background
2023-08-09 08:08:23,993.993 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Electricity Spot Rate in CZK/kWh' for cz_energy_spot_prices integration not ready yet; Retrying in background

2023-08-09 08:08:24,541.541 ERROR (MainThread) [custom_components.wattrouter] Error fetching information from /meas.xml - /meas.xml
2023-08-09 08:08:24,541.541 ERROR (MainThread) [custom_components.wattrouter] Unexpected error fetching wattrouter data: can only concatenate str (not "TypeError") to str
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\coordinator.py", line 36, in _async_update_data
    measurement=await self.api.get_measurement(),
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\api.py", line 48, in get_measurement
    return self.parser.parse_measurement(response_text)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\xml_parser.py", line 23, in parse_measurement
    root = ET.fromstring(xml)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\xml\etree\ElementTree.py", line 1342, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\coordinator.py", line 42, in _async_update_data
    _LOGGER.error("Error fetching data: " + exception)
TypeError: can only concatenate str (not "TypeError") to str
2023-08-09 08:08:24,541.541 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform wattrouter
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 563, in _async_add_entity
    device_info = entity.device_info
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\entity.py", line 66, in device_info
    identifiers={(DOMAIN, coordinator.data.measurement.serial_number)},
AttributeError: 'NoneType' object has no attribute 'measurement'
2023-08-09 08:08:24,635.635 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wattrouter platform for sensor
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 563, in _async_add_entity
    device_info = entity.device_info
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\entity.py", line 66, in device_info
    identifiers={(DOMAIN, coordinator.data.measurement.serial_number)},
AttributeError: 'NoneType' object has no attribute 'measurement'
2023-08-09 08:08:24,635.635 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform wattrouter
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 563, in _async_add_entity
    device_info = entity.device_info
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\entity.py", line 66, in device_info
    identifiers={(DOMAIN, coordinator.data.measurement.serial_number)},
AttributeError: 'NoneType' object has no attribute 'measurement'
2023-08-09 08:08:24,635.635 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mobile_app
2023-08-09 08:08:24,635.635 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up wattrouter platform for binary_sensor
Traceback (most recent call last):
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\entity_platform.py", line 563, in _async_add_entity
    device_info = entity.device_info
  File "D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\config\custom_components\wattrouter\entity.py", line 66, in device_info
    identifiers={(DOMAIN, coordinator.data.measurement.serial_number)},
AttributeError: 'NoneType' object has no attribute 'measurement'

**Comment by RSvorcik** [comment]
WATTconfig Mx   2.2

9. 8. 2023 9:55, 9:55, "Michal Baše" ***@***.***> napsal/a:

**Comment by yardee** [comment]
Jak jsem se ptal na URL wattrouteru, dáváte tam opravdu správně IP adresu? 
![image](https://github.com/yardee/ha-wattrouter/assets/10993234/065a4b9f-1d2d-4902-8776-c80bb4a5534a)

**Comment by yardee** [comment]
Verze je ok

**Comment by RSvorcik** [comment]
Ano dávám správnou IP adresu. Několikrát jsem to kontroloval včetně jména a hesla.

**Comment by yardee** [comment]
Vydal jsem novou verzi s lepším error handlingem, můžete zkusit? V logách by mělo být lépe vidět, co je blbě

**Comment by RSvorcik** [comment]
Tak tohle to píše
Home Assistant Core
Error setting up entry http://10.0.0.8/ for wattrouter
12:01:02 – (CHYBA) D:\Stažené soubory\HassWP_2023.5.3 čístá instalace - uprava 2\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py
Error fetching wattrouter data:
12:01:02 – (CHYBA) Wattrouter controller (vlastní integrace)
Error fetching data: a bytes-like object is required, not 'NoneType'
12:01:02 – (CHYBA) Wattrouter controller (vlastní integrace)
Error fetching information from http://10.0.0.8/meas.xml - Cannot connect to host 10.0.0.8:80 ssl:default [Vzdálený počítač odmítl síťové připojení]
12:01:02 – (CHYBA) Wattrouter controller (vlastní integrace)

**Comment by RSvorcik** [comment]
Aha už to asi chámu asi já mám port 8080. Port 80 mám už obsazený a nejde měnit.  Jak to mám změnit u Vás.

**Comment by yardee** [comment]
Mělo by stačit dát do URL port: http://10.0.0.8:8080/

**Comment by RSvorcik** [comment]
Děkuji moc za pomoc  mělo tam být  http://10.0.0.8:8080/. Už to funguje.
