### ISSUE TITLE
Zpracování hodnoty datumu

### ISSUE THREAD

**Issue by rpajik** [yardee/ha-wattrouter#8]
Home assistant 2023.8.1
Wattrouter MX s firmwarem 2.2

v logu HA se periodicky zobrazuje chyba - snaží se to zpracovat text s datumem jako integer

```
2023-08-06 10:57:54.527 WARNING (SyncWorker_6) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to XXX.XXX.XXX.XXX
2023-08-06 10:57:55.427 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2023-08-06'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/multiscrape/entity.py", line 114, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.wattrouter_date has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '2023-08-06' (<class 'str'>)

```

**Comment by yardee** [comment]
Nemáte to chybu v nastavení templaty pro multiscrape?
`  File "/config/custom_components/multiscrape/entity.py", line 114, in _handle_coordinator_update
`

**Comment by rpajik** [comment]
Tak to jsem opravdu přehlédl, multiscrape proti Wattrouteru jsem chtěl zrušil po přechodu na toto rozšíření a zůstalo mi to v konfiguraci. Díky za pomoc.
